Repository EXERLOG/exer_log, pull requests merged in 2022-08, with the labels that each got.

#93 BUGFIX: #86 #40
  .gitignore
  lib/UI/calendar/widgets/logout_button.dart
  lib/UI/workout/workout_page.dart
  lib/src/core/base/shared_preference/shared_pref_key.dart
  lib/src/feature/authentication/controller/authentication_controller.dart
  lib/src/feature/authentication/view/authentication_wrapper.dart
  lib/src/feature/authentication/view/landing_screen.dart
  lib/src/feature/onboarding/splash/view/splash_screen.dart
Labels: bug

#142 chore: update configuration for `mergeable`
  .github/mergeable.yml
  CODEOWNERS
Labels: enhancement

#148 fix: divide by 0 error when oneRepMax 0.0
  lib/UI/maxes/max_builder.dart
Labels: bug

#157 refactor: Calendar page refactored
  lib/UI/calendar/view/calendar_page.dart
  lib/UI/calendar/widgets/calendar_widget.dart
  lib/UI/calendar/widgets/date_widget.dart
  lib/src/core/base/extensions/context_extension.dart
  lib/src/dependency.dart
  lib/src/utils/text_constants.dart
Labels: bug, enhancement

#158 refactor: cleanup using USER_UID from shared preferences
  lib/Bloc/authentication.dart
  lib/Bloc/exercise_bloc.dart
  lib/Bloc/max_bloc.dart
  lib/Bloc/workout_bloc.dart
  lib/main.dart
  lib/src/core/base/shared_preference/shared_pref_key.dart
  lib/src/feature/authentication/controller/authentication_controller.dart
  lib/src/feature/onboarding/splash/view/splash_screen.dart
Labels: enhancement, refactoring

#159 refactor: part of general improvement
  lib/Bloc/authentication.dart
  lib/Bloc/email_signup.dart
  lib/UI/prev_workout/prev_workout_page.dart
  lib/UI/workout/workout_page.dart
  lib/src/feature/authentication/view/landing_screen.dart
  lib/src/feature/calendar/view/calendar_screen.dart
  lib/src/feature/calendar/widgets/calendar_widget.dart
  lib/src/feature/calendar/widgets/date_widget.dart
  lib/src/feature/calendar/widgets/logout_button.dart
  lib/src/feature/onboarding/splash/view/splash_screen.dart
  lib/src/widgets/dialogs.dart
Labels: enhancement, refactoring

#162 chore: fix reviewers in `mergeable` approval check
  .github/mergeable.yml
Labels: bug

#160 patch: Fix Navigation
  lib/UI/prev_workout/prev_workout_page.dart
  lib/UI/workout/workout_page.dart
Labels: bug, enhancement

#168 fix: custom FloatingActionButton
  lib/UI/exercise/exercise_card.dart
  lib/UI/workout/workout_page.dart
  lib/src/widgets/custom_floating_action_button.dart
Labels: bug
